### ISSUE TITLE
Feature Extractor

### ISSUE THREAD

**Issue by yh8899** [huailiang/face-nn#1]
我看到代码里面有“train_extractor”这个过程，但是在论文里面我没有找到相关介绍
![image](https://user-images.githubusercontent.com/5336422/68442385-c74f9a00-020b-11ea-86b3-62e9baebc080.png)
你能说明一下这个网络结构吗？不胜感激！

**Comment by huailiang** [comment]
你好 这是测试用的 论文里没提到
