### ISSUE TITLE
CFUtilPoolLib这个dll是干嘛用的啊，为什么XRoleParts组件继承MonoBehavior却在这个dll中

### ISSUE THREAD

**Issue by nongzhang** [huailiang/face-nn#12]
CFUtilPoolLib.dll主要处理的是哪个过程？

**Comment by huailiang** [comment]
XRoleParts 用来存一些骨骼的索引，不想运行时使用Find去查找， 所以预处理记录下来， 继承MonoBehaviour 是因为想把数据序列化在prefab中
