### ISSUE TITLE
能否上传一下您已经训练好的imitator模型

### ISSUE THREAD

**Issue by dake0805** [huailiang/face-nn#2]

**Comment by huailiang** [comment]
在引擎里裁掉头发的model:
 https://pan.baidu.com/s/1RWmvCJHOeXSFDxERQ26mUg
在引擎里完整显示头发、脖子等非脸的model:
 https://pan.baidu.com/s/1z0YvwsfBAFnhETjj0Zby-g

train中的效果参考视频：
 https://youtu.be/FKJ-rvXS39U
 https://www.bilibili.com/video/av75311069/
