### ISSUE TITLE
UnauthorizedAccessException in unity when generating dataset

### ISSUE THREAD

**Issue by cvenwu** [huailiang/face-nn#5]
![image](https://user-images.githubusercontent.com/24709251/71223554-478b1400-230f-11ea-8920-955b23a5e097.png)
Help, i don't how to solve this problem in unity. Baidu tells me to change the code. But i'm not sure.

**Comment by huailiang** [comment]
1. make sure the directory 'I:\wuxiaowen\face-nn-torch\export' that is exists. if not exist, create it
2. make sure you have access to operate the directory
