### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flynnamy** [huailiang/face-nn#8]
Hi，when I do inference, it has errors like this:size mismatch for 0.0.weight: copying a param with shape torch.Size([95, 512, 4, 4]) from checkpoint, the shape in current model is torch.Size([99, 512, 4, 4]). If I change params_cnt from 99 to 95, it will has a new error:index 96 is out of bounds for dimension 1 with size 95, because of self.argmax_params(t_params.data, 96, 3). What should I do? Changing argmax_param or could you please share model which is 99 dimension. Looking forward to your reply!@huailiang

**Comment by huailiang** [comment]
你好， 最初版本的是95个参数用来控制脸部骨骼， 后来又加了四个参数用来控制妆容， 你可以在Neurallnterface.cs(Unity编辑器工具)重新导出数据集， 然后重新train, 生成99个参数的模型， 然后再reinference.
